name: Build Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Build with pyinstaller
        run: poetry run pyinstaller --clean musa.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: musa-${{ matrix.os }}
          path: dist/musa*
