name: Build Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 'latest'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Build with pyinstaller
        run: poetry run python build_scripts.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Musa-${{ matrix.os }}
          path: dist/Musa*